function conn=connectToDVMax()
    %helper function to establish connection to DVMax oracle database. This
    %script centralizes code to make connection so that a single chage here
    %can update all checker scripts
    loadDatabaseDrivers()
    conn = database('ORPROD',...
                    'dvmax_lmiller',...
                    'dvmax',...
                    'Vendor','Oracle',...
                    'DriverType','thin',...
                    'Server','risdatprd.ci.northwestern.edu',...
                    'PortNumber',1521);

end