function conn=connectToDVMax()
    %helper function to establish connection to DVMax oracle database. This
    %script centralizes code to make connection so that a single chage here
    %can update all checker scripts
    loadDatabaseDrivers();
%     conn = database('ORPROD',...
%                     'dvmax_lmiller',...
%                     'dvmax',...
%                     'Vendor','Oracle',...
%                     'DriverType','thin',...
%                     'Server','risdatprd.ci.northwestern.edu',...
%                     'PortNumber',1521);
%     conn = database('ORPROD',...
%                     'dvmax_lmiller',...
%                     'dvmax',...
%                     'Vendor','Oracle',...
%                     'DriverType','thin',...
%                     'Server','risisisprdb.ci.northwestern.edu',...
%                     'PortNumber',1521);

    url = 'jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=risisisprdb.ci.northwestern.edu)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=ORPROD)))';
    driver='oracle.jdbc.driver.OracleDriver';
    username='dvmax_lmiller';
    password='dvmax';
    conn = database('databasename',username,password,driver,url)
end